export const COUPON_CODES = {
    BLACKFRIDAY: "BLACKFRIDAY",
    CYBERMONDAY: "CYBERMONDAY",
    NEWYEAR: "NEWYEAR",
    VALENTINES: "VALENTINES",
    SPRINGSALE: "SPRINGSALE",
    SUMMERSALE: "SUMMERSALE",
    FALLSALE: "FALLSALE",
    WINTERSALE: "WINTERSALE",
    BACKTOSCHOOL: "BACKTOSCHOOL",
    HALLOWEEN: "HALLOWEEN",
    THANKSGIVING: "THANKSGIVING",
    CHRISTMAS: "CHRISTMAS",
    EASTER: "EASTER",
    LABORDAY: "LABORDAY",
    MEMORIALDAY: "MEMORIALDAY",
    INDEPENDENCEDAY: "INDEPENDENCEDAY",
} as const;

export type CouponCode = keyof typeof COUPON_CODES;